### ISSUE TITLE
[로그인] jwt 토큰 - 웹 자동로그인

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#10]
현재 백엔드에서 `backend/adoorback/settings/base.py` 에 `'JWT_VERIFY': False`로 되어있는 상태인데, True로 변경했을 때 웹 자동로그인이 제대로 작동하는지 확인 필요

웹 자동로그인 해결 시 팀에게 공유해주고, 공유받은 내용 토대로 @koyrkr 가 앱 자동로그인 진행 예정

**Comment by GooJinSun** [comment]
`JWT_VERIFY`는 현재 사용하고 있지 않은 [`djangorestframework-jwt`](https://jpadilla.github.io/django-rest-framework-jwt/) 설정이라 현재 자동로그인과는 무관할 것 같습니다
(현재 사용하고 있는 인증방식은 [`djangorestframework-simplejwt`](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/) 입니다)

**Comment by GooJinSun** [comment]
현재 어도어의 인증 방식은 jwt 토큰 방식이 아닌 **세션 방식**으로 되어있음

- (클라이언트)토큰 요청 → (서버)access_token, refresh_token 발급
- (클라이언트)로그인 요청 →  (서버) sessionid를 발급
[이후 새로고침 시에]
- (클라이언트)refresh_token이 있나 확인
  - 없으면 /loign 페이지로 이동, 로그인 요청하면 다시 sessionid 발급
  - 있으면 요청한 페이지로 이동(/home, /questions, /anonymous 등)
- token으로 인증하고 있는 것 아닌가?
  - sessionid cookie를 지워보자. 로그아웃된다(세션으로 인증하고 있기 때문)
  - 토큰 인증에 필요한 access_token을 지워보자. 로그인이 유지된다(토큰은 삭제되었지만, 실제 인증에 사용하고 있는 세션이 만료되지 않았기 때문)
  - 백엔드에서 token을 통해 인증하는 코드가 없다...!
  - 벡엔드 settings.py에 세션이 브라우저가 닫히면 만료되도록 설정해보면 로그인이 유지되지 않는다
  
좀 더 자세한 정리 내용 -> [노션](https://www.notion.so/AS-IS-5abcca48e1044d02a086bdd14a0ae62e)

**Comment by GooJinSun** [comment]
웹/앱 멀티 플랫폼 인증을 위해서는 토큰 인증 방식이 필수적임
+ 기존 인증 방식(세션)을 토큰 방식의 인증으로 수정 필요(백/프론트 모두)

**Comment by ssm0318** [comment]
오와... 백엔드까지 짱 많이 알아봐줬네ㅠㅠ 정리 감사합니다 완전 이해가 쏙쏙됐음!!

**Comment by ssm0318** [comment]
프론트/백 토큰 방식 인증으로 변경하는거 진선이가 시도해볼만한/시도해보고 싶은건지 아닌지 알려주세여!

**Comment by GooJinSun** [comment]
더 급한 이슈 없으면, 이 이슈가 해결되어야 앱 쪽도 볼 수 있으니까 제가 봐볼게요!

**Comment by GooJinSun** [comment]
- bug
AS-IS: 로그인/회원가입 시 잘못된 정보 입력했을 때, 빨간 메시지가 보이지 않음
TO-BE: 400error(잘못된 정보 입력시) 빨간 메시지가 보여야 함(eg. 닉네임 혹은 비밀번호를 다시 확인해주세요!)
cc. @leesoojeong
