### ISSUE TITLE
[앱] 웹뷰간 navigate 문제

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#11]
**Describe the bug**
앱에서 웹뷰 페이지가 새로 떴을때 뒤로 갈 수 있는 방법이 없음

**To Reproduce**
1. 개인정보처리방침 페이지로 간다.
2. 뒤로 갈 수가 없다 ㅠㅠ

**Expected behavior**
위에 페이지 navigate 할 수 있는 TopBar가 있으면 좋을 것 같다!

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-05-07 at 13 31 28](https://user-images.githubusercontent.com/42240753/167238351-cc80eaa8-a847-4f29-a6e2-1e849e5f5c7d.png)

**Environment**

- Desktop [ ]
- Smartphone [x]

**Additional context**
개인정보처리방침 뿐 아니라 다른 웹페이지가 뜰 경우에 대비해서 미리 구현해두는 것이 좋을듯!

**Comment by GooJinSun** [comment]
@koyrkr 앱 관련 이슈는 앱 레포(https://github.com/koyrkr/adoor-app-cli/issues) 에 작성하는 건 어떨까요??

**Comment by koyrkr** [comment]
@GooJinSun 오 완전 좋아요! 그러는게 더 좋을 것 같아요! 거기로 옮겨두겠습니당!
