### ISSUE TITLE
[노티] 받은 질문 노티 확인 시 전체 노티 목록에서는 보이지 않던 잘못된/반복된 노티가 노출되는 버그

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#111]
**내용**
- 노티페이지의 '받은 질문' 탭 클릭시 친구A에게 받은 질문(Q1)이 n개가 중복되어 노출되고, (친구 A는 Q1을 n명의 친구에게 보냈다고 함)
- 내가 질문(Q2)을 N명의 친구에게 보냈을 때 보낸 질문까지도 나에게 질문(Q2)이 도착했다고 N개가 노출됨

**버그 재현 절차**

1. 질문 A를 친구 N명에게 보내본다
2. 노티 드랍다운 > 알림 전체 보기 클릭해서 노티 페이지로 이동 
3. '받은 질문'을 탭한다
4. 나에게 A라는 질문이 도착했다는 알림 N개가 도착한다

**정상 결과**
- 내가 보낸 질문(actor_id=나)는 받은 질문에 노출되면 안되고,
- 받은 질문에는 내가 받은 질문 노티만 포함되어야 한다

p.s. 프론트에서는 api 응답값을 그대로 노출하고 있어서 아마도 '받은 질문'에 해당하는 노티만을 보내주는 api(`api/notifications/response-requests/`)에 문제가 있는 것 같습니다. 확인 부탁드립니다! @njs03332 @h-yes-oo 

**이미지**
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37523788/204121229-4527fff4-6390-4741-b4bc-3908326ae00d.png">

**테스트 환경**
데스크탑

**Comment by njs03332** [comment]
확인해보니 노티 관련 이슈 작업이 반영되기 이전의 코드 (user tag 백엔드 브랜치) 에서는 재현되지 않는 걸로 봐서 (+ 제 기억으로도 해당 버그가 원래 없었던 것 같아요 !) @h-yes-oo 님께서 노티 이슈 해결하는 과정에서 생긴 버그일 것 같은데요..! 
혜수님이 확인해봐주실 수 있을까요 🙏🏻

**Comment by ssm0318** [comment]
그리구 이미 답한 질문은 받은 질문에 뜨지 않아야 합니다~ (지금은 이미 답한 과거 response request까지 전부 보이고 있는 상태에요)

진선이 스크린샷에서도 보이지만 동일 노티에 대해 일부는 read고 일부는 unread인 상태인 것도 확인 부탁드리구요,

비슷한 맥락에서 - 친구 요청도 여태까지 받았던 (이미 수락해서 없어졌어야 하는) 노티가 전부 보입니다. 왜 지나한테서 온 노티는 3개나 있는건지는 잘 모르겠네요. 실제로 3번 요청을 했던건지, 아니면 마지막에 있는 노티들은 뭔가 추가적인 이슈가 있는건지...?

![Screenshot 2022-11-27 at 11 48 55 AM](https://user-images.githubusercontent.com/25769209/204156481-199a258e-3b48-4a21-8721-5bf999dde310.png)

**Comment by GooJinSun** [comment]
> 확인해보니 노티 관련 이슈 작업이 반영되기 이전의 코드 (user tag 백엔드 브랜치) 에서는 재현되지 않는 걸로 봐서 (+ 제 기억으로도 해당 버그가 원래 없었던 것 같아요 !) @h-yes-oo 님께서 노티 이슈 해결하는 과정에서 생긴 버그일 것 같은데요..! 혜수님이 확인해봐주실 수 있을까요 🙏🏻

요거 추가적인 맥락 공유드립니다~

관련 API(`/api/notifications/friend-requests/`, `/api/notifications/response-requests/`)의 수정사항을 보니 마지막 수정이 8개월 전인걸로 보아 혜수님이 수정해주신 노티 작업 이전에도 발생했던 이슈인 것 같습니다!
이전에 해당 문제가 없었던(사실은 없어 보였던이 더 맞겠네요) 이유는 프론트에서 이 두 API를 사용하지 않고 있었기 때문입니다(이전에는 전체 노티 API('/api/notifictions/`)응답값에서 해당 타입(친구 요청/받은 질문)을 직접 필터링해서 보여주고 있었습니다)

https://github.com/ssm0318/adoor/pull/101 이 PR을 통해서 `/api/notifications/friend-requests/`, `/api/notifications/response-requests/` 두 API를 사용하도록 수정된 것이구요:)

관련 두 API를 확인해주시면 좋을 것 같습니다

**Comment by njs03332** [comment]
앗 그런 거였군요 !! 확인해주셔서 감사합니다!
저나 @h-yes-oo 중에 현재 진행중인 작업 빨리 끝나는 사람이 살펴보면 좋을 것 같네요 ㅎㅎ
우선 노션에 등록해두었습니다 (https://www.notion.so/jinsungoo/488cbff0f932462aa157fbee0db706ba)
