### ISSUE TITLE
[노티] 노티 모달 스크롤이 느리거나 작동을 안 할 때가 있음

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#122]
오늘 아침에 노티 모달에서 아무리 스크롤을 하고 기다려봐도 15개 이상 노티가 오지 않았는데 지금 다시 해보니 되기는 하네요.
근데 현재 구현 상으로는 1. 15개를 불러온다 2. 나머지를 전부 불러온다 순으로 콜이 되는 것 같은데 그러다 보니 2에서 시간이 너무 오래 소요되고 갈수록 느려진다는 문제가 있을 것 같아요. 
또 페북의 경우 다음 노티가 읽어와지길 기다리는 동안에 스크롤을 해도 화면 전체가 스크롤되지 않는데 다이버스의 경우 노티 모달 위에서 스크롤을 해도 전체 화면이 스크롤이 되어서 직관적이지 않은 거 같아요.
15개씩 불러오거나 최대 50개만 전달해주는 방식을 택할 수 있을 것 같아요.

동일하게 노티 모달 위에서 스크롤을 계속 했을 때의 반응입니다:

[페북]

https://user-images.githubusercontent.com/25769209/206020738-d0111839-b1ef-47db-9884-c6a6218ec248.mov

[다이버스]

https://user-images.githubusercontent.com/25769209/206020726-35c414d2-2126-465d-b83e-ad4f49fcea33.mov

**Comment by ssm0318** [comment]
https://user-images.githubusercontent.com/25769209/206877186-0b302176-47fb-4657-99a3-8c41ac52d4bb.mov

노티 모달이 스크롤되지 않은 현상을 다시 경험했습니다. 페이지를 새로고침을 하니까 잘 돼서 새로운 노티가 있고 그걸 전체읽음 처리를 한 후에 스크롤이 안 되는건가 싶기도 하구...

**Comment by GooJinSun** [comment]
@ssm0318 
이거 확인해보니 원래 기획은 노티 드랍다운은 무한 스크롤 없이 15개만 불러오고,
15개 이상 노티를 보고 싶을 때는 알림 전체 보기 클릭을 유도했던 것 같습니다

현재 종종 15개 이상의 노티가 보여지는 이유는 말씀하신대로 전체읽음 한 이후에 프론트에서 렌더링하는 노티 목록이 잘못 설정되어 있어서 그렇습니다! 원래는 15개까지만 스크롤되어야 했던...

둘 중에 원하는 방향성 알려주시면 수정하도록 하겠습니다:)

1. 노티 드랍다운에서 보여지는 노티는 15개로 유지한다
2. 노티 드랍다운에도 pagination, 무한 스크롤을 적용한다

**Comment by ssm0318** [comment]
원래 1이었다가 2로 변경을 해준 것 같아요! 누군지 모르겠지만 @h-yes-oo 인가?
근데 2가 좀 느려가지고 이 이슈를 처음 공유할 때 제안드린건 1&2의 타협안이에요!
노티 드랍다운에도 pagination을 적용하되, 노티를 최대 90?개까지만 불러온다

**Comment by GooJinSun** [comment]
변경한게 의도된건 아닌 것 같습니다!
그럼 15개 페이지네이션 + 최대 90개까지만 
으로 수정할게요:)
