### ISSUE TITLE
[노티] 친구요청 노티의 redirect_url이 username이 아닌 user_id로 되어있음

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#123]
**Describe the bug**
친구요청 노티의 redirect_url이 username이 아닌 user_id로 되어있음

**To Reproduce**

1. 누군가에게 친구요청을 받는다
2. 친구요청 노티를 클릭한다
3. users/:user_id로 리다이렉트 되어 존재하지 않는 사용자라는 페이지가 떠서 친구요청을 수락할 수 없다

**Expected behavior**
친구요청 노티의 redirect url은 username으로 구성되어야 한다

**Screenshots**
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/37523788/206360562-33676e48-e932-4a46-b395-596c4e8d86a3.png">

**Environment**

- Desktop [x]
- Smartphone [x]

**Additional context**

**Comment by ssm0318** [comment]
친구요청을 수락한 후 받는 '~와 친구가 되었습니다' 노티도 마찬가지입니다
