### ISSUE TITLE
[다국어][프론트] 서비스 다국어(영어) 지원 

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#132]

**Comment by njs03332** [comment]
요거는 백엔드/프론트 분리해서 이슈 작성해야 하는 걸까요~?

**Comment by GooJinSun** [comment]
@njs03332 네! 백엔드 이슈는 https://github.com/GooJinSun/diivers/issues/118 에 생성해두었습니다:)

작업하실 때 백/프론트 나눠서 이슈 생성 부탁드려요~!
(프론트/백 진행상황을 명확하게 알기 위함입니다! 혹시 더 좋은 방법이 있다면 언제든 의견주셔요!!)
cc/ @njs03332 @YejiAhn @h-yes-oo @koyrkr
