### ISSUE TITLE
[로그인] 자동로그인 안됨

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#138]

**Comment by ssm0318** [comment]
안드로이드 버전은 자동로그인 잘 되고 있는 것 같아요! Ios는 방나도 안 된다고 하네요 ㅠㅜ

**Comment by GooJinSun** [comment]
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/37523788/219931948-52cb5b0f-1f1a-4c65-b122-6a3d4fbb9e64.png">

"expire" "session"으로 설정되어 브라우저 환경마다 다르게 작동했던 것

> Cookies that 'expire at end of the session' expire unpredictably from the user's perspective!
> On iOS with Safari they expire whenever you switch apps!
> On Android with Chrome they don't expire when you close the browser.
> On Windows desktop running Chrome they expire when you close the browser. That's not when you close your website's tab; its when you close all tabs. Nor do they expire if there are any other browser windows open. If users run web apps as windows they might not even know they are browser windows. So your cookie's life depends on what the user is doing with some apparently unrelated app.
참고: https://stackoverflow.com/questions/4132095/when-does-a-cookie-with-expiration-time-at-end-of-session-expire

**Comment by GooJinSun** [comment]
cookie.set 할 때 expire date를 명시해주지 않으면 session으로 설정됨
> ;expires=date-in-GMTString-format: The expiry date of the cookie. If neither expires nor max-age specified it will expire at the end of session. [참고: [MDN] Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

> Define when the cookie will be removed. Value must be a [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) which will be interpreted as days from time of creation or a [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) instance. If omitted, the cookie becomes a session cookie. https://github.com/js-cookie/js-cookie#expires

**Comment by GooJinSun** [comment]
### 시도 1: cookie에 expires 설정하기
```js
// https://github.com/js-cookie/js-cookie#expires
import Cookies from 'js.cookie"
import { JWT_ACCESS_TOKEN } from '../constants/cookies';

Cookies.set(JWT_ACCESS_TOKEN, access, { expires: 7 });
```

여전히 session Cookie로 저장됨
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/37523788/219935371-bf57aad4-f7b8-451d-a407-a649d982a614.png">


### 시도 2: cookie에 expires 대신 custom option으로 max-age 설정하기
```js
// https://github.com/js-cookie/js-cookie/issues/633#issuecomment-638210333
import Cookies from 'js.cookie"
import { JWT_ACCESS_TOKEN } from '../constants/cookies';

Cookies.set(JWT_ACCESS_TOKEN, access, { 'max-age':  `${60*60*24*7}` });
```
여전히 session cookie로 저장..
<img width="839" alt="image" src="https://user-images.githubusercontent.com/37523788/219935464-e35be0ac-886d-47de-af06-c32b12720839.png">

-> client side에서 session 이상의 쿠키 유효기간 설정이 불가능한걸까?
