### ISSUE TITLE
[회원가입] 이메일 인증 프로세스 점검

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#148]

**Comment by GooJinSun** [comment]
https://myaccount.google.com/apppasswords?rapt=AEjHL4PbWeDP0n3Eo8eGmwcMCf3Dy0vDnuGBm6p-AjPM199UHeGe61YzJ0o9jqRy-UsQyfv7N-bnBtzbXu6iIRzXG14GRvSuCA

adoor.team 구글 앱 비밀번호 관련 이슈였음
cc/ @h-yes-oo

**Comment by ssm0318** [comment]
그럼 이슈가 없는건가요? close 해도 되는 것? @GooJinSun
