### ISSUE TITLE
[유저 페이지] 가운데 창 깨짐 현상

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#167]
메인 피드나 익명피드와 달리 사용자 페이지는 창 width를 줄일 시 깨지는 현상이 발생합니다.

https://user-images.githubusercontent.com/25769209/212750509-aa6d2421-e7f3-47b5-835a-9079f24d59e9.mov

**Comment by ssm0318** [comment]
왜인지 모르게 창 크기가 들쑥날쑥 하네요.! 원래 모두 일정하게 가운데에 모아져 있었는데 메인 피드는 창 전체를 차지하게 되었고 개별 질문 페이지는 로딩할 때의 스피너(?)도, 로딩된 창도 크기가 특이하네요! 유저페이지는 작게 나왔다가 커져유
아 그리고 개별 질문 페이지가 노티에서 질문을 받아서 클릭해서 들어갈 경우에는 아래 녹화본처럼 작게 나오고 해당 질문에 답변을 작성한 후에는 다시 창 전체를 차지하네요!

https://user-images.githubusercontent.com/25769209/212968410-2cbcaaec-18c7-4ff3-ae5b-8747518b58b8.mov

**Comment by ssm0318** [comment]
원래의 창이 어땠는지 참고할 수 있는 곳: [링크](https://drive.google.com/drive/u/2/folders/1-OiSjPFORFgv4tXhUtgWRUCxVWbsautb)

**Comment by koyrkr** [comment]
@ssm0318 오오 넵! 레포팅 감사합니다! 
아마 제가 이전에 레이아웃을 한번 바꾸고 나서 전체적으로 깨지는 부분들이 생긴 것 같아요!
말씀해주신 케이스 포함해서 수정하겠습니다~!
