### ISSUE TITLE
[사용자 검색] 사용자 검색 후 검색 내역이 로그아웃해도 남아있음

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#17]
**Describe the bug**
A 계정으로 로그인 후 사용자 검색 후, 로그아웃 후에 B 계정으로 로그인하면 사용자 검색 이력이 남아있음

**To Reproduce**
1. A 계정 로그인
2. 사용자 검색 뒤, 텍스트 필드 그대로 둔채 로그아웃
3. B 계정 로그인
4. 사용자 검색 창 텍스트 필드에 내역 그대로 남아있음

**Expected behavior**
사용자 검색 창 텍스트 필드가 비어있어야 함

**Screenshots**

**Environment**

- Desktop [O]
- Smartphone [X]

**Additional context**
일단은 데스크톱에서만 일어나는 이슈 (Header.tsx)
하지만 고쳐두는게 좋을 것 같긴해서 남겨둠!

**Comment by GooJinSun** [comment]
`develop`브랜치에 머지되어(https://github.com/ssm0318/adoor/pull/21) close 합니다~
