### ISSUE TITLE
[프로필] 이미지 추가 시 400*400 이미지 외에도 등록 가능하도록 수정

### ISSUE THREAD

**Issue by 2hyunji** [ssm0318/adoor#191]
ASIS
사이즈 큰 이미지 업로드 시 
[이미지의 크기가 너무 큽니다. 400 * 400 이하 크기의 이미지를 사용해주세요] 라는 알럿이 떠서 
이미지 크기를 맞춰서 업로드 하지 않는 이상 이미지 등록이 불가함

TOBE
사이즈가 큰 이미지 업로드 시 
400*400으로 자동 크롭하여 + 센터 정렬 적용하여 프로필 이미지 업로드 됨

**Comment by koyrkr** [comment]
프론트 400 * 400 validation도 잘 되고 있는지 다시 한번 체크 필요!
