### ISSUE TITLE
[노티] 최근 노티 모달 노출 오류

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#2]
**Describe the bug**
안 읽은 노티가 있는데 가장 최근 노티 15개를 이미 읽었을 경우 노티에 빨간 불이 안 들어옴
1. 노티 모달 눌러도 스크롤이 안됨
2. 노티 전체보기 페이지로 가서 안 읽은 노티까지 스크롤을 하면 그제서야 빨간 불이 들어옴

**To Reproduce**
1. 언제나 재현됨

**Expected behavior**
- 안 읽은 노티가 있으면 항상 빨간 불이 나와야 함 (노티 모달, 노티 전체보기 페이지 전부)
- 노티 모달 스크롤이 되어야 함

**Screenshots**
<img width="1078" alt="Screen Shot 2022-04-16 at 2 09 50 PM" src="https://user-images.githubusercontent.com/42240753/166098023-f23de91e-d0c1-43ee-bc37-f849e53f7a09.png">
<img width="472" alt="Screen Shot 2022-04-16 at 2 09 43 PM" src="https://user-images.githubusercontent.com/42240753/166098028-5de54c97-ef4a-4c2f-add3-33e5cc901830.png">
<img width="403" alt="Screen Shot 2022-04-16 at 2 09 35 PM" src="https://user-images.githubusercontent.com/42240753/166098030-bad05ff8-9b24-41b5-8293-8808802c9c15.png">

**Desktop (please complete the following information):**
 
(나중에 수정 부탁드려용 @ssm0318)
 - OS: 모름
 - Browser: chrome
 - Version: 모름

**Smartphone (please complete the following information):**
모름

**Additional context**
없음

**Comment by ssm0318** [comment]
노티 뱃지에 노티 갯수를 적어줘도 좋을 것 같아요! [노티 크롬 익스텐션](https://chrome.google.com/webstore/detail/adoor%EC%96%B4%EB%8F%84%EC%96%B4-notification-ala/iogboadjfafhpmphocbhepblaecbmnlk)처럼요~

**Comment by GooJinSun** [comment]
@koyrkr 

> 노티 모달 눌러도 스크롤이 안됨

혹시 모달의 스크롤이 안된다는 것의 의미가 '15개 이상' 노티가 보여지고 나서의 상황을 말씀하신걸까요?
![Nov-13-2022 18-13-36](https://user-images.githubusercontent.com/37523788/201514520-8ad67f57-c071-45f3-ae75-e4e58596ee7d.gif)
(크롬/사파리 모두 스크롤이 잘 되고 있는 것 같습니다!)

**Comment by GooJinSun** [comment]
노티창 오픈 시 모두 읽음 처리되도록 수정되면, 이 이슈는 해결될 것 같네요:)

cc/ @h-yes-oo
