### ISSUE TITLE
[모바일] iOS 앱 상단바(?) 채우기

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#217]
![image](https://user-images.githubusercontent.com/25769209/224559383-0d583ea1-d82c-441c-acc7-3381636e4621.png)
![image](https://user-images.githubusercontent.com/25769209/224559387-37b99a61-f16a-4f70-b880-baabd533ae75.png)
요런 앱들과 달리 저희 앱에서의 노치 부분이랑 하단바 밑이 비어있습니다. 요 부분을 채워넣을 수 있으면 더 앱처럼 보일 것 같아요!
![image](https://user-images.githubusercontent.com/25769209/224559506-bf2c0a17-fee0-4961-9c28-91d6bbe0299f.png)

**Comment by GooJinSun** [comment]
app 레포에 생성하여 닫습니다
https://github.com/GooJinSun/diivers-app-cli/issues/9
