### ISSUE TITLE
[Bug Fix] 노티창에서 다음 노티를 받아오는 데에 시간이 오래 걸리는 이슈

### ISSUE THREAD

**Issue by h-yes-oo** [ssm0318/adoor#226]
**내용**
헤더의 노티창에서 다음 노티를 받아오는 데에 시간이 오래 걸리는 이슈가 있습니다.
다음 노티를 불러오는 동안 노티창에서 스크롤을 하는 경우, 노티창 하단에 더이상 노티가 남아있지 않기 때문에 메인 페이지가 스크롤되는 현상이 발생합니다. 
다음 노티를 불러오는 데에 대략 2초의 시간이 걸려 개선이 필요합니다.

**버그 재현 절차**

1. 헤더의 노티 창을 클릭한다.
2. 아래로 계속 스크롤 해본다.

**정상 결과**

**이미지**
![화면 기록 2023-03-18 오전 10 37 06](https://user-images.githubusercontent.com/43427306/226077581-40b2ba42-3456-4d27-8b19-b3b1bef12325.gif)

**테스트 환경**
지금까지 받은 노티 개수가 많은 경우, 데스크탑에서 재현 가능합니다.

**Comment by ssm0318** [comment]
[링크](https://drive.google.com/file/d/1OCA4KatW64cKzEmvkDWGGD--1ILvjwrD/view?usp=share_link)
이곳에서 안 읽은 알림이 있는 상태에서의 영상 확인하실 수 있습니다. (보통은 이렇게까지 오래 걸리지는 않는데 오늘 특별히 더 오래걸리는 것 같습니다)
후반부에서 노티 전체보기 창에서의 스크롤도 확인하실 수 있습니다.
