### ISSUE TITLE
[Bug] home 피드에서 게시글/댓글/답글을 남기거나 삭제해도 바로 업데이트 되지 않음

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#236]
**내용**
- #142 에서 friend feed에 react-query를 적용한 이후에 나타나는 버그
**버그 재현 절차**
1. 홈 피드에서 댓글 혹은 답글을 단다
2. 댓글/답글이 바로 업데이트 되지 않는다
3. 새로고침 하면 달았던 댓글이 보인다

**정상 결과**
댓글/답글을 달자마자 바로 댓글/답글이 업데이트 되어야 한다

**테스트 환경**
데스크탑

- [x] 댓글 달기
- [x] 답글 달기
- [ ] `postKey` 확인하기
- [x] 댓글 삭제
- [x] 답글 삭제
- [x] 게시글 삭제
- [x] 게시글 작성

**Comment by ssm0318** [comment]
Home에서 게시글을 작성해도 새로고침을 하거나 새로운 게시글을 달아야만 달리는 것 같아요
게시글1 작성 -> 게시글1 안 보임 -> 게시글2 작성 -> 게시글1 보이고 게시글2 안 보임 -> 게시글3 작성 -> 게시글2 보이고 게시글3 안 보임

유사한 작업일 것 같아 코멘트로 달아요
