### ISSUE TITLE
[앱] 푸시 알림 켜는 버튼 추가

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#241]
앱을 설치하고 처음 열었을 때 푸시 알림 관련 설정을 선택하도록 되어있으나
푸시 알림이 필요한지 고민해보지 않고 거절하는 유저들이 많을 것으로 생각이 되어
앱 사용 도중 푸시 알림을 받아보는 설정을 켜고 싶어지는 유저들이 좀 더 손쉽게 해당 설정을 조정할 수 있도록
shortcut을 만들어주면 좋을 것 같습니다.

**Comment by GooJinSun** [comment]
@ssm0318 앱 관련 이슈는 https://github.com/GooJinSun/diivers-app-cli/issues/10 요기 레포에 생성 부탁드려요!
https://github.com/GooJinSun/diivers-app-cli/issues/10 앱 레포에 생성하여 이 이슈는 닫습니다~
