### ISSUE TITLE
[Bug] 게시글 작성 시 익명피드에 노출됨

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#245]
**내용**
현재 article을 게시할 시 익명피드에도 게시가 됩니다. 답변이 아닌 게시글은 익명피드에 노출되지 않아야 합니다.

**버그 재현 절차**

1. Article을 게시한다.
2. 익명피드에 노출이 된다.
3. 공개 범위 수정 불가

**정상 결과**

**이미지**
https://user-images.githubusercontent.com/25769209/226215289-bdaafd21-79b8-4489-8ab8-926cacd9ac67.mov

**테스트 환경**
데스크탑 & 모바일

**Comment by GooJinSun** [comment]
@ssm0318 요것도 다시 재현될까요?

**Comment by ssm0318** [comment]
@GooJinSun 넵!
