### ISSUE TITLE
[Bug] 게시글 수정 시 다른 게시글 내용이 열림

### ISSUE THREAD

**Issue by YejiAhn** [ssm0318/adoor#246]
**내용**
게시글 수정 시 다른 게시글 내용이 열림

**버그 재현 절차**

1. 마이 피드에 들어간다
2. 게시글 수정을 누른다

**정상 결과**
해당 게시글 내용이 나와야 한다

**이미지**
![B9CF96B7-F0FD-4E55-9098-4A8A581A823D](https://user-images.githubusercontent.com/35886730/226366719-5892ad89-3805-44de-ac16-0d3d00baf454.gif)

**테스트 환경**
모바일

**Comment by koyrkr** [comment]
저도 재현되는 것 확인이요!
뭔가 게시글을 새로 작성한 뒤 그 게시글을 수정할 때 생기는 문제같기도 하네요!

**Comment by YejiAhn** [comment]
확인 감사합니다! 
![756C8889-1C42-4214-A434-EE14BBD96E42](https://user-images.githubusercontent.com/35886730/226383199-5562ced3-cffc-4a06-97e6-a029c512df90.gif)
예전 게시글(2023/01/27)도 똑같은 현상 발생하는 것 같네요 😭
