### ISSUE TITLE
[Bug] 답변 작성 시 draft에 저장이 되고 익명피드에도 공개됨

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#247]
**내용**
질문에 친구공개로 답변을 하는 경우에 draft에 저장이 되고 익명피드에도 공개가 됩니다.
스크린 레코딩을 하기 전에는 답변을 포스팅한 후 메인 피드에서 제 글을 볼 수 없는 이슈도 있었는데, 해당 부분은 어떻게 재현이 가능한지 확인하지 못했습니다.

**버그 재현 절차**
1. 질문에 답변 작성
2. 친구 공개로 게시

**정상 결과**

**이미지**
https://user-images.githubusercontent.com/25769209/226507484-0a20258b-98c9-47a4-8c7d-ed41fb77126f.mov

**테스트 환경**
데스크탑 - 크롬

**Comment by GooJinSun** [comment]
- [x] 질문에 ~친구공개로~ 답변을 하는 경우 draft에 저장이 된다
- [x] 익명피드에도 공개된다 #255 에서 해결 완
- [x] 답변 포스팅 후 메인 피드에서 글을 볼 수 없는 이슈 -> react-query 캐싱 이슈

**Comment by GooJinSun** [comment]
재현됨(재원 모바일)

https://user-images.githubusercontent.com/37523788/229316754-fede42b6-5b86-458f-a766-f2f3daecf24c.MP4

재현안됨(진선 모바일)

https://user-images.githubusercontent.com/37523788/229318790-eba9527e-caae-4cbb-94ee-c51d806fe603.MP4|

**Comment by GooJinSun** [comment]
진선폰+재원 계정으로 확인해본 결과 정상 작동

https://user-images.githubusercontent.com/37523788/229319894-e50688e8-2ef2-487b-8466-3f7ae1fbdd2a.MP4

**Comment by GooJinSun** [comment]
js 캐싱 문제로 추정됨
-> 배포 이후 js 캐싱 이슈로 반영이 안되는 문제가 없도록 조치 필요

**Comment by GooJinSun** [comment]
https://user-images.githubusercontent.com/37523788/229320138-409a15b1-81ba-4c82-a41c-6c4bb47aef28.mov


는 데스크탑 + slow 3g 환경에서도 재현됨

feed refetch가 완료되지 않은 상태에서 이전에 홈피드 캐싱된 걸 보여주고 있음
