### ISSUE TITLE
[노티 모달] 노출 순서 오류 

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#4]
**Describe the bug**
이슈인지는 모르겠으나 알림이 시간순이 아닌 이유가 있나요?

**To Reproduce**
1. 노티 아이콘 클릭
2. 노티 모달 노출
3. 노티 노출 순서 최신순이 아닌 것 확인 가능
4. 새로고침해도 똑같이 노출

**Expected behavior**
노티 모달의 알림 노출은 최신순으로 노출되어야 함

**Screenshots**
![image](https://user-images.githubusercontent.com/42240753/167233091-d711ad59-2ec1-4427-bbf8-b48c9fb9ec3d.png)

**Desktop (please complete the following information):**

(나중에 업데이트해주세용 @leesoojeong )
 - OS: 모름
 - Browse: 모름
 - Version: 모름

**Smartphone (please complete the following information):**
해당 없음

**Additional context**
없음

**Comment by GooJinSun** [comment]
노티 리스트 API인 `/notifications`에서 최신순 정렬이 되지않은 상태의 리스트를 보내줍니다
<img width="934" alt="image" src="https://user-images.githubusercontent.com/37523788/169643149-26045948-a6c1-4ac6-ba85-61ba7c0dc280.png">
혹시 백에서 정렬해서 보내주는 것이 어렵다면 프론트쪽에서 정렬해보겠습니다 @ssm0318
