### ISSUE TITLE
[로그인] 로그인 및 무한 로딩 오류 

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#5]
**Describe the bug**
로그인 하는데 2분이 걸리고 로딩하는데 30초가 걸린다

**To Reproduce**
1. 어도어 켜두고 다른 브라우저에서 뭐 다른거 하다가 다시 어도어 돌아와서 새로고침하면 바로 재현 가능
2. 로그인이 거의 80%의 확률로 안되고 있는 중

**Expected behavior**
언제든지 로그인이 잘 되고, 무한 로딩 문제도 없어야 함

**Screenshots**
없음

**Desktop (please complete the following information):**
 - OS: 상관없음
 - Browser 상관없음
 - Version 상관없음

**Smartphone (please complete the following information):**
기기 종류 상관없이 재현

**Additional context**
없음

**Comment by GooJinSun** [comment]
자동로그인 문제라기 보다는 SSL 인증 관련 문제일 듯???

<img width="940" alt="image" src="https://user-images.githubusercontent.com/37523788/169641847-e0b7ec40-fcf0-4068-9297-1d7200439d59.png">
https://stackoverflow.com/questions/37919706/why-is-the-initial-connection-time-for-a-http-request-so-long

> The initial connection refers to the time taken to perform the initial TCP handshake and negotiating an SSL (where applicable). The slowness could be caused by congestion, where the server has hit a limit and can't respond to new connections while existing ones are pending. You could look into some [performance enhancements](https://www.nginx.com/blog/10-tips-for-10x-application-performance/) in your Nginx configuration.

**Comment by GooJinSun** [comment]
이후 또 발생하면 re-open 하는 걸로~
