### ISSUE TITLE
[리팩토링] 프론트엔드 파일 구조 리팩토링

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#55]
1. components 폴더 안에 page 컴포넌트도 전부 넣고
    1. 상단 위로 올려야한는 건 _ prefix 붙여서
        1. ex. _components
2. **components**
    1. **_common**
    2. **_mobile**
        1. **mobile-drawer**
            1. MobileDrawer.jsx
        2. **mobile-search-page**
            1. MobileSearchpage.jsx
    3. **friend-feed**
        1. **post**
            1. Post.jsx
            2. Post.styles.js 
                1. (styles 관련 파일은 밖으로 빼는걸로 : makeStyles & styled 전부)
            3. Post.test.js
        2. …
        3. FriendFeed.jsx (실제 페이지 컴포넌트)
3. **history, store, apis** → **utils**로 옮기기
    1. **utils**
        1. **test** 
            1. store.js
            2. apis.js
            3. …
        2. .. 다른 util은 전부 파일로 관리
4. **modules** → 테스트 파일이 있으니 폴더로 전부 관리
    1. **friend**
    2. **like**
    3. **loading**
    4. …
5. **public**
    1. **assets** 
        1. **logo**
        2. **icon**

**Comment by koyrkr** [comment]
[참고 노션 링크](https://www.notion.so/jinsungoo/Directory-3066c840f0604f59abcb2b4c2a94ac2b#59d995eaf8c44200b7b7718f0d38c779)
