### ISSUE TITLE
[노티] 헤더의 안 읽은 노티 존재 여부 표시가 부정확함

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#70]
**Describe the bug**
가장 최신 노티 15개 중에 안 읽은 노티가 없을 경우
그 이전 노티 중 읽지 않은 노티가 존재해도
헤더에는 안 읽은 노티가 있다는 표시가 뜨지 않음

**To Reproduce**
노티를 받은 후 읽지 않고 쌓아둔다. 20개쯤 쌓인 후 최신 15개를 전부 클릭해서 확인한다.

**Expected behavior**
읽지 않은 노티 5개가 있음에도 노티 표시가 뜨지 않는다.

**Screenshots**
<img width="442" alt="Screen Shot 2022-10-09 at 6 09 58 PM" src="https://user-images.githubusercontent.com/25769209/194788086-0b7d3953-b211-4956-b4b8-fff25ab4a0b1.png">
chrome extension 상으로는 안 읽은 노티가 4개인데 헤더에는 노티 표시가 없음.

**Environment**

- Desktop [x]
- Smartphone [x]

**Additional context**

**Comment by GooJinSun** [comment]
#2 와 중복된 이슈로 close 합니다
