### ISSUE TITLE
[추천질문] 추천질문위젯이 피드와 겹쳐보이는 이슈

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/adoor#83]
**Describe the bug**
왼쪽의 추천 질문 위젯과 피드가 데스크톱에서 아래와 같이 화면 크기가 모바일 & 데스크톱 사이일때 겹쳐보입니다!

![image](https://user-images.githubusercontent.com/42240753/197394539-df59aa0f-dfa4-4d15-b7f7-1477e14531e0.png)

현재는 우선 임시방편으로 아래와 같이 수정된 상태이지만,

![image](https://user-images.githubusercontent.com/42240753/197394567-b09f05c1-19f7-41de-a4d9-cfe024228965.png)

조금 더 나은 방법이 있을 것 같아서 최선의 방향을 고민해보고 반영하고자 이슈로 따로 올립니다! 

**To Reproduce**
1. 데스크톱 버전에서 adoor에 접속한다.
2. 화면의 너비를 점점 줄여본다.

**Expected behavior**
(더 나은 방향이 있을 것 같은데.. 고민이 필요합니다!)

**Screenshots**

**Environment**

- Desktop [x]
- Smartphone [ ]

**Additional context**
@leesoojeong 의 의견도 함께 들어보면 좋을 것 같습니당!

**Comment by ssm0318** [comment]
https://user-images.githubusercontent.com/25769209/206877213-43a77ef9-7de8-46de-843c-f545b8bc5021.mov

모바일처럼 노티랑 햄버거바는 항상 떠있을 수 있도록 하는 것도 필요할 것 같아요! 
어느 정도 너비 이내로 줄어들면 질문 위젯을 없앤다던지?
지금은 화면 절반을 차지하도록 했을때 사용성이 좋지 않네요 ㅠㅠ
