### ISSUE TITLE
[노티] 답글(<-댓글과 다름) 노티 오류

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#84]
**Describe the bug**
제가 단 댓글에 대한 답글을 받았을 때 해당 답글에 대한 노티를 받지 못했습니다.

**To Reproduce**
답글 노티가 올 때도 있는데 안 오는 경우가 있음 -> 댓글에 대한 노티를 누른 것과 충돌이 된 것일까?

**Expected behavior**
댓글에 좋아요를 누른 뒤 답글을 남겨도 노티가 제대로 와야 함

**Screenshots**
![Screen Shot 2022-10-29 at 3 46 44 PM](https://user-images.githubusercontent.com/25769209/198855305-670b8376-e8a7-49d1-9b53-959f17de2d3a.png)

**Environment**

- Desktop [x]
- Smartphone [x]

**Additional context**

**Comment by h-yes-oo** [comment]
댓글 노티가 매번 생성되는 것이 아니라 업데이트 되는 방식이라 발생한 문제로 추정됩니다 ! 필터링 로직에 이슈가 있어서 지나님이 재원님의 댓글에 좋아요를 누르면서 발생한 좋아요 노티에 의해 답글 노티가 생성되지 않은 것으로 보입니다.

해당 이슈 재현되는 것을 확인하였고, [(#48) 댓글 작성 시 항상 새로운 노티를 생성하도록 수정](https://github.com/ssm0318/adoor/pull/106) 작업 이후 재현되지 않는 것을 확인하여 이슈 닫도록 하겠습니다.
