### ISSUE TITLE
[회원가입][백엔드] 회원가입 동선 개선

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/adoor#92]
논의 완료 후 업데이트 드리겠습니다.
논의 중간 과정은 이곳에서 확인 가능: https://www.figma.com/file/56M4wZDsZkvIHri0d6UMvb/Sign-Up?node-id=0%3A1

**Comment by njs03332** [comment]
해당 이슈는 회원가입 오류 문구 변경 + 회원가입 동선 변경 모두 진행하는 걸로 이해하면 될까요~?  @ssm0318 

@GooJinSun signup_renew 라는 브랜치 생성해뒀고 signup_renew-back 에서 작업 시작하려고 합니다 ! 
프론트도 여기서 따서 진행하시면 될 것 같아용 (아직 안하신 거 맞죠..?! 혹시나 해서..)
