### ISSUE TITLE
[좋아요] 좋아요를 누르고 취소하고 새로고침 하면, 좋아요가 다시 생겨있음

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/adoor#93]
좋아요를 누르고 취소하고 새로고침하면 좋아요가 다시 생겨 있음
![Nov-06-2022 14-53-28](https://user-images.githubusercontent.com/37523788/200156475-e1ce772c-86d6-4c5c-bb4b-c04cd45bea47.gif)

cc. @njs03332

**Comment by njs03332** [comment]
#53 도 이것과 관련 있는듯 !!
